<a href="https://colab.research.google.com/github/Jozefina-Gramatikova/Find_the_handwritten_numbers/blob/main/Handwritten_numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np

In [67]:
import pandas as pd

In [68]:
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal as mvn

In [69]:
#importing google drive
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [82]:
df = pd.read_csv('/content/gdrive/MyDrive/Jozefina Gramatikova - MNIST_train.csv' )

In [83]:
df.columns

Index(['Unnamed: 0', 'index', 'labels', '0', '1', '2', '3', '4', '5', '6',
       ...
       '774', '775', '776', '777', '778', '779', '780', '781', '782', '783'],
      dtype='object', length=787)

In [87]:
df.drop(['index', 'Unnamed: 0'], axis=1, inplace=True)

In [88]:
df

labels  0  1  2  3  4  5  6  7  8  ...  774  775  776  777  778  779  \
0           5  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
1           0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
2           4  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
3           1  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
4           9  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
...       ... .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...   
59995       8  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
59996       3  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
59997       5  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
59998       6  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
59999       8  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   

       780  781  782  783  
0        0    0    0    0  
1        0    0    0    0  
2        0    0    0    0  
3        0    0    0    0  
4        0    0    0    0  
...    ...  ...  ...  ...  
59995    0    0    0    0  
59996    0    0    0    0  
59997    0    0    0    0  
59998    0    0    0    0  
59999    0    0    0    0  

[60000 rows x 785 columns]

In [90]:
X = df.to_numpy()

In [91]:
X

array([[5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [8, 0, 0, ..., 0, 0, 0]])

In [93]:
y=X[:,0]

In [94]:
y

array([5, 0, 4, ..., 5, 6, 8])

In [95]:
X=X[:,0  :  ]

In [96]:
X

array([[5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [8, 0, 0, ..., 0, 0, 0]])

In [97]:
y.shape

(60000,)

In [98]:
X.shape

(60000, 785)

In [99]:
class GaussNB(): #Gaussian Naive Baise

  def fit(self, X, y, epsilon=1e-3): #the fit method X, y - test labels; self creates a global variable withing the class its like a memory
    self.likelihoods = dict()
    self.priors = dict()

    self.K = set(y.astype(int))

    for k in self.K:
      X_k = X[y==k,:] #we only want the class where y=k

      #we are going to populate our likelihoods
      self.likelihoods[k]={"mean": X_k.mean(axis=0), 'cov': X_k.var(axis=0)+ epsilon} #var=variance=sigma
      self.priors[k] = len(X_k)/len(X)

  def predict(self, X):

    N, D = X.shape
    P_hat = np.zeros((N, len(self.K))) #predicted probability
    
    for k,l in self.likelihoods.items():
      P_hat[:,k] = mvn.logpdf(X, l['mean'], l['cov']+np.log(self.priors[k])) #probability density function

    return P_hat.argmax(axis=1)


In [100]:
gnb = GaussNB()

In [101]:
gnb.fit(X,y)

In [102]:
y_hat=gnb.predict(X)

ValueError: ignored