<a href="https://colab.research.google.com/github/Jozefina-Gramatikova/Find_the_handwritten_numbers/blob/main/Handwritten_numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal as mvn

In [ ]:
#importing google drive
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
data = pd.read_csv('/content/gdrive/MyDrive/Jozefina Gramatikova - MNIST_train.csv' )

In [ ]:
data # we do have a header


Unnamed: 0  index  labels  0  1  2  3  4  5  6  ...  774  775  776  \
0               0      0       5  0  0  0  0  0  0  0  ...    0    0    0   
1               1      1       0  0  0  0  0  0  0  0  ...    0    0    0   
2               2      2       4  0  0  0  0  0  0  0  ...    0    0    0   
3               3      3       1  0  0  0  0  0  0  0  ...    0    0    0   
4               4      4       9  0  0  0  0  0  0  0  ...    0    0    0   
...           ...    ...     ... .. .. .. .. .. .. ..  ...  ...  ...  ...   
59995       59995  59995       8  0  0  0  0  0  0  0  ...    0    0    0   
59996       59996  59996       3  0  0  0  0  0  0  0  ...    0    0    0   
59997       59997  59997       5  0  0  0  0  0  0  0  ...    0    0    0   
59998       59998  59998       6  0  0  0  0  0  0  0  ...    0    0    0   
59999       59999  59999       8  0  0  0  0  0  0  0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 787 columns]

In [ ]:
X = data.to_numpy()

In [ ]:
X

array([[    0,     0,     5, ...,     0,     0,     0],
       [    1,     1,     0, ...,     0,     0,     0],
       [    2,     2,     4, ...,     0,     0,     0],
       ...,
       [59997, 59997,     5, ...,     0,     0,     0],
       [59998, 59998,     6, ...,     0,     0,     0],
       [59999, 59999,     8, ...,     0,     0,     0]])

In [ ]:
y = X[:, -1] #the last column

In [ ]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
X=X[:,:-1] #from the beginning to the last one

In [ ]:
X

array([[    0,     0,     5, ...,     0,     0,     0],
       [    1,     1,     0, ...,     0,     0,     0],
       [    2,     2,     4, ...,     0,     0,     0],
       ...,
       [59997, 59997,     5, ...,     0,     0,     0],
       [59998, 59998,     6, ...,     0,     0,     0],
       [59999, 59999,     8, ...,     0,     0,     0]])

In [ ]:
y.shape

(60000,)

In [ ]:
X.shape

(60000, 786)

In [ ]:
data.dtypes

Unnamed: 0    int64
index         int64
labels        int64
0             int64
1             int64
              ...  
779           int64
780           int64
781           int64
782           int64
783           int64
Length: 787, dtype: object

In [ ]:
data.head(5)   

Unnamed: 0  index  labels  0  1  2  3  4  5  6  ...  774  775  776  777  \
0           0      0       5  0  0  0  0  0  0  0  ...    0    0    0    0   
1           1      1       0  0  0  0  0  0  0  0  ...    0    0    0    0   
2           2      2       4  0  0  0  0  0  0  0  ...    0    0    0    0   
3           3      3       1  0  0  0  0  0  0  0  ...    0    0    0    0   
4           4      4       9  0  0  0  0  0  0  0  ...    0    0    0    0   

   778  779  780  781  782  783  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 787 columns]

In [ ]:
first_column = data.columns[0]

In [ ]:
data.head(5)   

Unnamed: 0  index  labels  0  1  2  3  4  5  6  ...  774  775  776  777  \
0           0      0       5  0  0  0  0  0  0  0  ...    0    0    0    0   
1           1      1       0  0  0  0  0  0  0  0  ...    0    0    0    0   
2           2      2       4  0  0  0  0  0  0  0  ...    0    0    0    0   
3           3      3       1  0  0  0  0  0  0  0  ...    0    0    0    0   
4           4      4       9  0  0  0  0  0  0  0  ...    0    0    0    0   

   778  779  780  781  782  783  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 787 columns]

In [ ]:
data = data.drop(['index','labels'], axis=1) #dropping 'index' and 'labels' from the dataset


In [ ]:
data.head(5)   

Unnamed: 0  0  1  2  3  4  5  6  7  8  ...  774  775  776  777  778  779  \
0           0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
1           1  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
2           2  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
3           3  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
4           4  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   

   780  781  782  783  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0  

[5 rows x 785 columns]

In [ ]:
data = data.drop([first_column], axis=1)


In [ ]:
data.head(5)   

0  1  2  3  4  5  6  7  8  9  ...  774  775  776  777  778  779  780  781  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   782  783  
0    0    0  
1    0    0  
2    0    0  
3    0    0  
4    0    0  

[5 rows x 784 columns]

In [ ]:
print(data.isnull().sum())

0      0
1      0
2      0
3      0
4      0
      ..
779    0
780    0
781    0
782    0
783    0
Length: 784, dtype: int64


In [ ]:
data.max()

0       0
1       0
2       0
3       0
4       0
       ..
779    62
780     0
781     0
782     0
783     0
Length: 784, dtype: int64

In [ ]:
data['0'].max()

0

In [49]:
class GaussNB(): #Gaussian Naive Baise

  def fit(self, X, y, epsilon=1e-3): #the fit method X, y - test labels; self creates a global variable withing the class its like a memory
    self.likelihoods = dict()
    self.priors = dict()

    self.K = set(y.astype(int))

    for k in self.K:
      X_k = X[y==k,:] #we only want the class where y=k

      #we are going to populate our likelihoods
      self.likelihoods[k]={"mean": X_k.mean(axis=0), 'cov': X_k.var(axis=0)+ epsilon} #var=variance=sigma
      self.priors[k] = len(X_k)/len(X)

  def predict(self, X):

    N, D = X.shape
    P_hat = np.zeros((N, len(self.K))) #predicted probability
    
    for k,l in self.likelihoods.items():
      P_hat[:,k] = mvn.logpdf(X, l['mean'], l['cov']+np.log(self.priors[k])) #probability density function

    return P_hat.argmax(axis=1)


In [50]:
gnb = GaussNB()

In [51]:
gnb.fit(X,y)

In [52]:
y_hat=gnb.predict(X)

LinAlgError: ignored

In [53]:
X

array([[    0,     0,     5, ...,     0,     0,     0],
       [    1,     1,     0, ...,     0,     0,     0],
       [    2,     2,     4, ...,     0,     0,     0],
       ...,
       [59997, 59997,     5, ...,     0,     0,     0],
       [59998, 59998,     6, ...,     0,     0,     0],
       [59999, 59999,     8, ...,     0,     0,     0]])

In [54]:
X.shape

(60000, 786)